---
- name: "Download {{ font_pack.zip_name }}"
  ansible.builtin.get_url:
    url: "{{ font_pack.url }}"
    dest: "/tmp/{{ font_pack.zip_name }}"
    mode: '0644'


- name: "Create temporary extract directory /tmp/{{ font_pack.extract_dir }}"
  ansible.builtin.file:
    path: "/tmp/{{ font_pack.extract_dir }}"
    state: directory
    mode: '0755'


- name: "Extract {{ font_pack.zip_name }}"
  ansible.builtin.unarchive:
    src: "/tmp/{{ font_pack.zip_name }}"
    dest: "/tmp/{{ font_pack.extract_dir }}"
    remote_src: yes

- name: "Create font directory {{ font_pack.font_dir }}"
  ansible.builtin.file:
    path: "{{ font_pack.font_dir }}"
    state: directory
    mode: '0755'

- name: "Copy fonts to {{ font_pack.font_dir }}"
  ansible.builtin.shell:
    cmd: "cp /tmp/{{ font_pack.extract_dir }}/{{ font_pack.src_path }} {{ font_pack.font_dir }}/"
  changed_when: true

- name: "Clean up {{ font_pack.zip_name }} and extracted files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ font_pack.zip_name }}"
    - "/tmp/{{ font_pack.extract_dir }}"