---
- name: Download Google Chrome .deb package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: '0644'
  become: true

- name: Install Google Chrome from .deb package
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  become: true

- name: Check Google Chrome version
  ansible.builtin.command:
    cmd: google-chrome --version
  register: chrome_version
  changed_when: false
  become: true

- name: Display Google Chrome version
  ansible.builtin.debug:
    msg: "Google Chrome version installed: {{ chrome_version.stdout }}"
  become: true