---
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set up Docker repository (alternative)
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: yes

- name: Ensure Python 3 and pip are installed
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Ensure Docker Python module is installed
  pip:
    name: docker
    state: present

- name: Create Qdrant storage directory
  file:
    path: "{{ qdrant_storage_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Run Qdrant container
  community.docker.docker_container:
    name: qdrant
    image: qdrant/qdrant:latest
    state: started
    restart_policy: always
    published_ports:
      - "6333:6333"
    volumes:
      - "{{ qdrant_storage_dir }}:/qdrant/storage"

- name: Create Qdrant collection 'files1024'
  uri:
    url: "http://{{ qdrant_host }}:6333/collections/files1024"
    method: PUT
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      vectors:
        size: 1024
        distance: "Cosine"
    status_code: 200