---
- name: Ensure config directory exists (recursive)
  ansible.builtin.file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Stop and disable the web service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
    daemon_reload: yes

- name: Conditionally download latest build
  when: update | bool
  block:
    - name: Validate that client is provided
      fail:
        msg: "--client must be provided when --update=1"
      when: client | length == 0

    - name: Download build archive
      ansible.builtin.get_url:
        url: "{{ archive_url_base }}/web-{{ client }}.tar.gz"
        dest: "{{ archive_path }}"
        mode: '0644'

- name: Backup existing build directory (if exists)
  ansible.builtin.shell: |
    timestamp=$(date +%Y-%m-%d_%H-%M-%S)
    cp -raf {{ target_dir }}/build {{ target_dir }}/../oldfiles/web-build-$timestamp
  ignore_errors: true

- name: Save env.js if it exists
  ansible.builtin.copy:
    src: "{{ target_dir }}/build/config/env.js"
    dest: "{{ config_dir }}/env.js"
    remote_src: yes
  ignore_errors: true

- name: Remove current build directory
  ansible.builtin.file:
    path: "{{ target_dir }}/build"
    state: absent

- name: Extract new build archive
  ansible.builtin.unarchive:
    src: "{{ archive_path }}"
    dest: "{{ target_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=0]

- name: Restore env.js if it was saved
  ansible.builtin.copy:
    src: "{{ config_dir }}/env.js"
    dest: "{{ target_dir }}/build/config/env.js"
    remote_src: yes
  ignore_errors: true

- name: Set ownership to appadmin
  ansible.builtin.file:
    path: "{{ target_dir }}"
    state: directory
    recurse: yes
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Enable and start the web service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for port 3000 to be open
  ansible.builtin.wait_for:
    port: 3000
    host: 127.0.0.1
    timeout: 10
    state: started

- name: Perform healthcheck
  ansible.builtin.uri:
    url: http://localhost:3000/healthcheck
    method: GET
    return_content: yes
    status_code: 200