---
- name: Download InfluxData GPG key
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /tmp/influxdata-archive.key
    mode: '0644'

- name: Verify checksum of InfluxData GPG key
  ansible.builtin.shell: |
    echo "943666881a1b8d9b849b74caebf02d3465d6beb716510d86a39f6c8e8dac7515  /tmp/influxdata-archive.key" | sha256sum -c -
  register: checksum_result
  failed_when: "'OK' not in checksum_result.stdout"

- name: Convert InfluxData GPG key to GPG format
  ansible.builtin.command: gpg --dearmor -o /etc/apt/trusted.gpg.d/influxdata-archive.gpg /tmp/influxdata-archive.key
  args:
    creates: /etc/apt/trusted.gpg.d/influxdata-archive.gpg
  become: true

- name: Add InfluxData APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main'
    filename: influxdata
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present

- name: Ensure Telegraf config directory exists
  ansible.builtin.file:
    path: /opt/telegraf
    state: directory
    mode: '0755'

- name: Deploy Telegraf config to /opt
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /opt/telegraf/telegraf.conf
    mode: '0644'

- name: Create systemd override directory for Telegraf
  ansible.builtin.file:
    path: /etc/systemd/system/telegraf.service.d
    state: directory
    mode: '0755'

- name: Create Telegraf systemd override to use config from /opt
  ansible.builtin.copy:
    dest: /etc/systemd/system/telegraf.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/telegraf --config /opt/telegraf/telegraf.conf
    mode: '0644'

- name: Reload systemd and restart Telegraf
  ansible.builtin.systemd:
    daemon_reload: true
    name: telegraf
    enabled: true
    state: restarted